[api]
port = 58337

# winston File transport options
# see https://github.com/winstonjs/winston/blob/master/docs/transports.md#file-transport
[log]
filename = "telegram-updates.log"
prettyPrint = false
timestamp = true
json = false

[oauth]
clientId = ""
clientSecret = ""

# ex: http://example.com/oauthcallback
redirectUrl = ""

# send a /token command to your bot and open the link
# to start the flow that gives you the refreshToken value
refreshToken = ""
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.readonly"
]

[telegram]
token = ""
username = ""
admins = ["fczuardi"]

[sheet]
# the share url of a google sheet
url = ""

# Columns to be used as questions and get user input,
# the range should include 3 extra adjacent columns
# to be filled with metadata: timestamp, userId, tgFrom.
#
# Example: if your form questions goes from A1 to H1 on the
# spreadsheet you need to add 3 columns after that and
# setup the dataRange to be A1:K
dataRange = "Sheet1!A1:K"

# Which column to look for the approved state.
# Example: if the status column is A, the value is 1
# if the status column is H, the value is 8
userStatusColumn = 8

# The value in the status column to consider an user approved
userApprovedValue = "Approved"

