[api]
port = 58337

# winston File transport options
# see https://github.com/winstonjs/winston/blob/master/docs/transports.md#file-transport
[log]
filename = "telegram-updates.log"
prettyPrint = false
timestamp = true
json = false

[oauth]
clientId = ""
clientSecret = ""

# ex: http://example.com/oauthcallback
redirectUrl = ""

# send a /token command to your bot and open the link
# to start the flow that gives you the refreshToken value
refreshToken = ""
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.readonly"
]

[telegram]
token = ""
username = ""
admins = ["fczuardi"]

[sheets]
# the share url of a google sheet
url = ""

[sheets.user]
# a table with 4 columns to use for the application for
# first column is the variable, second is a short caption
# third is an input question and optionally a 4th column
# with multiple choice answer separated by the | character
questions = "Questions User!A2:D"

# remember to leave 3 extra adjacent columns free
# for telegram metadata and include those extra 3 columns in the range
# example, if your form has 9 questions, from A to I, your
# range needs to go from A to L
answers = "Answers Users!A2:L2"

# what range to look for user application status
status = "'Users Statuses'!A2:C"

# Which columns to look for the userId and approved state.
# Example: if the status column is A, the value is 0
# if the status column is H, the value is 7
statusUserId = 0
statusColumn = 1

# The value in the status column to consider an user approved
approvedValue = "Approved"

[sheets.school]
questions = "Questions School!A2:D11"

# Google drive variables
[drive]

# This the root ID number that can be found on folder url.
# ie:. https://drive.google.com/drive/some_path/{{rootId}}
rootId = ""

# path variable used inside program to save temp data.
# don't forget to create this folder
tempFolder = ""

# Those are the parameters used when making the request to google drive's
# API service
[drive.fields]
corpus = "user"
orderBy = "folder"
pageSize = 1000
fields = "files(fileExtension,fullFileExtension,id,kind,mimeType,name,originalFilename,ownedByMe,parents,trashed),kind,nextPageToken"

